using System;
using System.Runtime.InteropServices;

namespace agora
{
    namespace unity
    {
        public interface BaseInterface
        {   
            // ServerMessage create(ServerMessage message);
            // ServerMessage DeleteEngine(ServerMessage message);
            // ServerMessage GetSdkVersion();
            // ServerMessage JoinChannel(ServerMessage message);            
            // ServerMessage SetLocalVoicePitch(ServerMessage message);            
            // ServerMessage SetRemoteVoicePosition(ServerMessage message);            
            // ServerMessage SetVoiceOnlyMode(ServerMessage message);           
            // ServerMessage LeaveChannel();            
            // ServerMessage EnableLastmileTest();            
            // ServerMessage DisableLastmileTest();            
            // ServerMessage enableVideo();            
            // ServerMessage disableVideo();           
            // ServerMessage enableLocalVideo(ServerMessage message);            
            // ServerMessage EnableLocalAudio(ServerMessage message);            
            // ServerMessage setupLocalVideo(ServerMessage message);            
            // ServerMessage setupRemoteVideo(ServerMessage message);            
            // ServerMessage setLocalRenderMode(ServerMessage message);           
            // ServerMessage setRemoteRenderMode(ServerMessage message);            
            // ServerMessage setLocalVideoMirrorMode(ServerMessage message);
            // ServerMessage startPreview();            
            // ServerMessage stopPreview();  
            // ServerMessage EnableAudio();     
            // ServerMessage DisableAudio();          
            // ServerMessage SetParameters(ServerMessage message);          
            // ServerMessage GetCallId();
            // // caller free the returned char * (through freeObject)
            // ServerMessage Rate(ServerMessage message);            
            // ServerMessage Complain(ServerMessage message);            
            // ServerMessage setEnableSpeakerphone(ServerMessage message);            
            // ServerMessage IsSpeakerphoneEnabled();           
            // ServerMessage setDefaultAudioRoutetoSpeakerphone(ServerMessage message);           
            // ServerMessage EnableAudioVolumeIndication(ServerMessage message);        
            // ServerMessage StartAudioRecording(ServerMessage message);         
            // ServerMessage StartAudioRecording2(ServerMessage message);           
            // ServerMessage StopAudioRecording();           
            // ServerMessage StartAudioMixing(ServerMessage message);           
            // ServerMessage StopAudioMixing();           
            // ServerMessage PauseAudioMixing();            
            // ServerMessage ResumeAudioMixing();           
            // ServerMessage AdjustAudioMixingVolume(ServerMessage message);           
            // ServerMessage GetAudioMixingDuration();            
            // ServerMessage GetAudioMixingCurrentPosition();           
            // ServerMessage MuteLocalAudioStream(ServerMessage message);           
            // ServerMessage MuteAllRemoteAudioStreams(ServerMessage message);            
            // ServerMessage MuteRemoteAudioStream(ServerMessage message);           
            // ServerMessage switchCamera();           
            // ServerMessage setVideoProfile(ServerMessage message);           
            // ServerMessage muteLocalVideoStream(ServerMessage message);           
            // ServerMessage muteAllRemoteVideoStreams(ServerMessage message);            
            // ServerMessage muteRemoteVideoStream(ServerMessage message);            
            // ServerMessage SetLogFile(ServerMessage message);           
            // ServerMessage RenewToken(ServerMessage message);            
            // ServerMessage SetChannelProfile(ServerMessage message);           
            // ServerMessage SetClientRole(ServerMessage message);            
            // ServerMessage enableDualStreamMode(ServerMessage message);           
            // ServerMessage SetEncryptionMode(ServerMessage message);            
            // ServerMessage SetEncryptionSecret(ServerMessage message);           
            // ServerMessage StartRecordingService(ServerMessage message);           
            // ServerMessage StopRecordingService(ServerMessage message);            
            // ServerMessage RefreshRecordingServiceStatus();            
            // ServerMessage CreateDataStream(ServerMessage message);
            // // TODO! supports general data later. now only string is supported           
            // ServerMessage SendStreamMessage(ServerMessage message);            
            // ServerMessage SetSpeakerphoneVolume(ServerMessage message);           
            // ServerMessage AdjustRecordingSignalVolume(ServerMessage message);            
            // ServerMessage AdjustPlaybackSignalVolume(ServerMessage message);            
            // ServerMessage SetHighQualityAudioParametersWithFullband(ServerMessage message);            
            // ServerMessage EnableInEarMonitoring(ServerMessage message);           
            // ServerMessage EnableWebSdkInteroperability(ServerMessage message);            
            // ServerMessage SetVideoQualityParameters(ServerMessage message);           
            // ServerMessage StartEchoTest();           
            // ServerMessage StartEchoTest2(ServerMessage message);            
            // ServerMessage StopEchoTest();           
            // ServerMessage setRemoteVideoStreamType(ServerMessage message);            
            // ServerMessage SetMixedAudioFrameParameters(ServerMessage message);           
            // ServerMessage SetAudioMixingPosition(ServerMessage message);
            // // setLogFilter: deprecated           
            // ServerMessage SetLogFilter(ServerMessage message);
            // // video texture stuff (extension for gaming)            
            // ServerMessage EnableVideoObserver();            
            // ServerMessage DisableVideoObserver();           
            // ServerMessage GenerateNativeTexture();            
            // ServerMessage UpdateTexture(ServerMessage message);           
            // ServerMessage DeleteTexture(ServerMessage message);            
            // ServerMessage UpdateVideoRawData(ServerMessage message);           
            // ServerMessage AddUserVideoInfo(ServerMessage message);            
            // ServerMessage RemoveUserVideoInfo(ServerMessage message);            
            // ServerMessage SetPlaybackDeviceVolume(ServerMessage message);           
            // ServerMessage GetEffectsVolume();           
            // ServerMessage SetEffectsVolume(ServerMessage message);            
            // ServerMessage PlayEffect(ServerMessage message);           
            // ServerMessage StopEffect(ServerMessage message);            
            // ServerMessage StopAllEffects();            
            // ServerMessage PreloadEffect(ServerMessage message);           
            // ServerMessage UnloadEffect(ServerMessage message);            
            // ServerMessage PauseEffect(ServerMessage message);            
            // ServerMessage PauseAllEffects();           
            // ServerMessage ResumeEffect(ServerMessage message);            
            // ServerMessage ResumeAllEffects();            
            // ServerMessage SetDefaultMuteAllRemoteAudioStreams(ServerMessage message);            
            // ServerMessage SetDefaultMuteAllRemoteVideoStreams(ServerMessage message);           
            // ServerMessage FreeObject(ServerMessage message);           
            // ServerMessage GetConnectionState();                        
            // ServerMessage SetAudioProfile(ServerMessage message);                    
            // ServerMessage SetVideoEncoderConfiguration(ServerMessage message);
            // ServerMessage AdjustAudioMixingPlayoutVolume(ServerMessage message);
            // ServerMessage AdjustAudioMixingPublishVolume(ServerMessage message);
            // ServerMessage SetVolumeOfEffect(ServerMessage message);
            // ServerMessage SetRecordingAudioFrameParameters(ServerMessage message);  
            // ServerMessage SetPlaybackAudioFrameParameters(ServerMessage message); 
            // ServerMessage SetLocalPublishFallbackOption(ServerMessage message);        
            // ServerMessage SetRemoteSubscribeFallbackOption(ServerMessage message);
            // ServerMessage SetRemoteDefaultVideoStreamType(ServerMessage message);
            // ServerMessage AddPublishStreamUrl(ServerMessage message);
            // ServerMessage RemovePublishStreamUrl(ServerMessage message);
            // ServerMessage GetErrorDescription(ServerMessage message);
            // ServerMessage SetLiveTranscoding(ServerMessage message);
            // ServerMessage CreateAVideoDeviceManager();
            // ServerMessage ReleaseAVideoDeviceManager();
            // ServerMessage StartVideoDeviceTest(ServerMessage message);
            // ServerMessage StopVideoDeviceTest();
            // ServerMessage GetVideoDeviceCollectionCount();
            // ServerMessage GetVideoDeviceCollectionDevice(ServerMessage message);
            // ServerMessage SetVideoDeviceCollectionDevice(ServerMessage message);
            // ServerMessage GetCurrentVideoDevice(ServerMessage message);
            // ServerMessage CreatAAudioRecordingDeviceManager();
            // ServerMessage ReleaseAAudioRecordingDeviceManager();
            // ServerMessage GetAudioRecordingDeviceCount();
            // ServerMessage GetAudioRecordingDevice(ServerMessage message);
            // ServerMessage SetAudioRecordingDevice(ServerMessage message); 
            // ServerMessage SetAudioRecordingDeviceVolume(ServerMessage message);
            // ServerMessage GetAudioRecordingDeviceVolume();
            // ServerMessage SetAudioRecordingDeviceMute(ServerMessage message);
            // ServerMessage IsAudioRecordingDeviceMute(); 
            // ServerMessage GetCurrentRecordingDeviceInfo(ServerMessage message);
            // ServerMessage GetCurrentRecordingDevice(ServerMessage message);      
            // ServerMessage StartAudioRecordingDeviceTest(ServerMessage message);         
            // ServerMessage StopAudioRecordingDeviceTest();
            // ServerMessage GetAudioPlaybackDeviceCount();   
            // ServerMessage CreatAAudioPlaybackDeviceManager();        
            // ServerMessage ReleaseAAudioPlaybackDeviceManager();         
            // ServerMessage GetAudioPlaybackDevice(ServerMessage message);   
            // ServerMessage SetAudioPlaybackDevice(ServerMessage message);          
            // ServerMessage SetAudioPlaybackDeviceVolume(ServerMessage message);           
            // ServerMessage GetAudioPlaybackDeviceVolume();
            // ServerMessage SetAudioPlaybackDeviceMute(ServerMessage message);
            // ServerMessage IsAudioPlaybackDeviceMute();
            // ServerMessage StartAudioPlaybackDeviceTest(ServerMessage message);
            // ServerMessage StopAudioPlaybackDeviceTest();   
            // ServerMessage GetCurrentPlaybackDeviceInfo(ServerMessage message);       
            // ServerMessage GetCurrentPlaybackDevice(ServerMessage message);    
            // ServerMessage PushVideoFrame(ServerMessage message);      
            // ServerMessage SetExternalVideoSource(ServerMessage message);       
            // ServerMessage SetExternalAudioSource(ServerMessage message);
            // ServerMessage PushAudioFrame(ServerMessage message);
            // ServerMessage RegisterVideoRawDataObserver();         
            // ServerMessage UnRegisterVideoRawDataObserver();         
            // ServerMessage RegisterAudioRawDataObserver();           
            // ServerMessage UnRegisterAudioRawDataObserver();        
            // ServerMessage SetRenderMode(ServerMessage message);         
            // ServerMessage GetAudioMixingPlayoutVolume();   
            // ServerMessage GetAudioMixingPublishVolume();       
            // ServerMessage SetLocalVoiceChanger(ServerMessage message);     
            // ServerMessage SetLocalVoiceReverbPreset(ServerMessage message);     
            // ServerMessage EnableSoundPositionIndication(ServerMessage message);    
            // ServerMessage SetLocalVoiceEqualization(ServerMessage message);
            // ServerMessage SetLocalVoiceReverb(ServerMessage message);  
            // ServerMessage SetCameraCapturerConfiguration(ServerMessage message);      
            // ServerMessage SetRemoteUserPriority(ServerMessage message);      
            // ServerMessage SetLogFileSize(ServerMessage message);       
            // ServerMessage SetExternalAudioSink(ServerMessage message);      
            // ServerMessage PullAudioFrame(ServerMessage message);      
            // ServerMessage StartLastmileProbeTest(ServerMessage message);       
            // ServerMessage StopLastmileProbeTest();
            // ServerMessage ConfigPublisher(ServerMessage message);  
            // ServerMessage AddVideoWatermark(ServerMessage message);    
            // ServerMessage AddVideoWatermark2(ServerMessage message);
            // ServerMessage ClearVideoWatermarks();        
            // ServerMessage RegisterLocalUserAccount(ServerMessage message);        
            // ServerMessage JoinChannelWithUserAccount(ServerMessage message);
            // ServerMessage GetUserInfoByUserAccount(ServerMessage message);         
            // ServerMessage GetUserInfoByUid(ServerMessage message);        
            // ServerMessage SetBeautyEffectOptions(ServerMessage message);    
            // ServerMessage SetInEarMonitoringVolume(ServerMessage message);     
            // ServerMessage StartScreenCaptureByDisplayId(ServerMessage message);      
            // ServerMessage StartScreenCaptureByScreenRect(ServerMessage message);       
            // ServerMessage SetScreenCaptureContentHint(ServerMessage message);       
            // ServerMessage UpdateScreenCaptureParameters(ServerMessage message);          
            // ServerMessage UpdateScreenCaptureRegion(ServerMessage message);         
            // ServerMessage StopScreenCapture();
            // ServerMessage AddInjectStreamUrl(ServerMessage message);       
            // ServerMessage RemoveInjectStreamUrl(ServerMessage message);         
            // ServerMessage EnableLoopbackRecording(ServerMessage message);       
            // ServerMessage SetAudioSessionOperationRestriction(ServerMessage message);
            // ServerMessage SwitchChannel(ServerMessage message);
            // ServerMessage StartChannelMediaRelay(ServerMessage message);
            // ServerMessage UpdateChannelMediaRelay(ServerMessage message);   
            // ServerMessage StopChannelMediaRelay();
            // ServerMessage SendMetadata(ServerMessage message);
            // ServerMessage RegisterPacketObserver();
            // ServerMessage UnRegisterPacketObserver();     
            // ServerMessage RegisterMediaMetadataObserver(ServerMessage message);
            // ServerMessage UnRegisterMediaMetadataObserver();
            // ServerMessage SetMirrorApplied(ServerMessage message);
            // ServerMessage StartScreenCaptureByWindowId(ServerMessage message);
        }
    }
}